# Required powershell
version: "3"

tasks:
  default:
    - task: help

  help:
    silent: true
    cmds:
      - task -l

  build:dev: npm run dev

  build: npm run build

  watch: watchexec --exts "js,json,css" cp main.js styles.css manifest.json $USERPROFILE/work/minerva/.obsidian/plugins/obsidian-smart-search/

  dev:
    desc: Build and copy files when they are updated.
    deps: [build:dev, watch]

  release:
    desc: |
      Build
          ∟ [Ex] task release VERSION=1.2.3
    deps:
      - build
    cmds:
      - |
        sed -i -r 's/\"version\": \".+\"/\"version\": \"{{.VERSION}}\"/g' manifest.json
      - git add manifest.json
      - git commit -m "Update manifest"
      - npm version {{.VERSION}}
      - task: build
      - git push --tags
      - git push
    preconditions:
      - sh: "[ {{.VERSION}} != '' ]"
        msg: "VERSION is required."
