name: "Release"

on: workflow_dispatch
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      # conventionalcommits v10はrelease notesが空になるバグがあるため9.3.1に固定
      # https://github.com/semantic-release/release-notes-generator/issues/992
      - run: npm i -D --no-save conventional-changelog-conventionalcommits@9.3.1 @semantic-release/git@10.0.1 @semantic-release/exec@7.1.0
      - uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
